GET {{url}}

###
GET {{url}}/notes/{{id}}

###
POST {{url}}/notes
Content-Type: application/json

{
  "authorId": "AU1033123",
  "title": "Note title",
  "text": "This is note text",
  "createdAt": "2023-04-28T23:41:00Z"
}

###
GET {{url}}/notes?author_id=AU1033123
